workouse_digital_wallet_plugin_admin:
  resource: "@WorkouseSyliusDigitalWalletPlugin/Resources/config/admin_routing.yml"
  prefix: /admin

workouse_digital_wallet_plugin_shop:
  resource: "@WorkouseSyliusDigitalWalletPlugin/Resources/config/shop_routing.yml"
  prefix: /{_locale}
  requirements:
    _locale: ^[a-z]{2}(?:_[A-Z]{2})?$

workouse_digital_wallet_customer_credit_use:
  path: /shop-api/credit/use
  defaults:
    _controller: WorkouseSyliusDigitalWalletPlugin:Wallet:useCredit

workouse_digital_wallet_customer_credit_remove:
    path: /shop-api/credit/remove
    defaults:
        _controller: WorkouseSyliusDigitalWalletPlugin:Wallet:removeCredit

3attar_sylius_wallet_plugin_shop_account_index:
    path: /{_locale}/wallet/index
    methods: [GET]
    defaults:
        _controller: WorkouseSyliusDigitalWalletPlugin:Wallet:indexWallet
        _sylius:
            section: shop_account
            template: "@WorkouseSyliusDigitalWalletPlugin/shop/index.html.twig"
