workouse_digital_wallet_plugin_admin:
  resource: "@WorkouseSyliusDigitalWalletPlugin/Resources/config/admin_routing.yml"
  prefix: /admin

workouse_digital_wallet_plugin_shop:
  resource: "@WorkouseSyliusDigitalWalletPlugin/Resources/config/shop_routing.yml"
  prefix: /{_locale}
  requirements:
    _locale: ^[a-z]{2}(?:_[A-Z]{2})?$

workouse_digital_wallet_customer_credit_use:
  path: /shop-api/credit/use
  defaults:
    _controller: WorkouseSyliusDigitalWalletPlugin:Wallet:useCredit
