eres_digital_wallet_plugin_admin:
  resource: "@AcmeSyliusExamplePlugin/Resources/config/admin_routing.yml"
  prefix: /admin

eres_digital_wallet_plugin_shop:
  resource: "@AcmeSyliusExamplePlugin/Resources/config/shop_routing.yml"
  prefix: /{_locale}
  requirements:
    _locale: ^[a-z]{2}(?:_[A-Z]{2})?$
