services:
  workouse_digital_wallet.listener.admin.customer.show.menu_builder:
    class: Workouse\DigitalWalletPlugin\Menu\AdminCustomerShowMenuListener
    tags:
      - { name: kernel.event_listener, event: sylius.menu.admin.customer.show, method: addAdminCustomerShowMenuItems }

  workouse_digital_wallet.block_event_listener.sylius.shop.account.dashboard.after_information:
    class: Sylius\Bundle\UiBundle\Block\BlockEventListener
    arguments:
      - 'WorkouseDigitalWalletPlugin:shop:customer_credit_block.html.twig'
    tags:
      - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.account.dashboard.after_information, method: onBlockEvent }

  workouse_digital_wallet.wallet_service:
    class: Workouse\DigitalWalletPlugin\Service\WalletService
    public: true
    arguments:
      - '@security.helper'
      - '@doctrine.orm.default_entity_manager'
      - '@sylius.currency_converter'
      - '@sylius.context.currency'
      - '@sylius.factory.adjustment'

  workouse_digital_wallet.block_event_listener.sylius.shop.cart.summary.totals:
    class: Sylius\Bundle\UiBundle\Block\BlockEventListener
    arguments:
      - 'WorkouseDigitalWalletPlugin:shop:cart_summary_credit.html.twig'
    tags:
      - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.cart.summary.totals, method: onBlockEvent }

  workouse_digital_wallet.promotion:
    class: Workouse\DigitalWalletPlugin\Service\PromotionService
    public: true
    arguments:
      - '@doctrine.orm.entity_manager'
      - '%workouse_digital_wallet.referrer%'
      - '%workouse_digital_wallet.invitee%'
