services:
  eres_digital_wallet.listener.admin.customer.show.menu_builder:
    class: Acme\SyliusExamplePlugin\Menu\AdminCustomerShowMenuListener
    tags:
      - { name: kernel.event_listener, event: sylius.menu.admin.customer.show, method: addAdminCustomerShowMenuItems }

  eres_digital_wallet.block_event_listener.sylius.shop.account.dashboard.after_information:
    class: Sylius\Bundle\UiBundle\Block\BlockEventListener
    arguments:
      - 'AcmeSyliusExamplePlugin:shop:customer_credit_block.html.twig'
    tags:
      - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.account.dashboard.after_information, method: onBlockEvent }

  eres_digital_wallet.wallet_service:
    class: Acme\SyliusExamplePlugin\Service\WalletService
    public: true
    arguments:
      - '@security.helper'
      - '@doctrine.orm.default_entity_manager'
      - '@sylius.currency_converter'
      - '@sylius.context.currency'

  eres_digital_wallet.block_event_listener.sylius.shop.cart.summary.totals:
    class: Sylius\Bundle\UiBundle\Block\BlockEventListener
    arguments:
      - 'AcmeSyliusExamplePlugin:shop:cart_summary_credit.html.twig'
    tags:
      - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.cart.summary.totals, method: onBlockEvent }
